# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33bd5fc555dce9d6cc79b2078c364fe4b7e3f4f7d9b5018448d51c78491bb76cffe729c88c10896c082c44428281b52df3c9c003ce41e4d85c8583a0c4da8c9d

test:
  secret_key_base: 29e8382785b6880a0343f285538e72009576f60425e1be7b7329b8df490a9e01ac516ad221215eade373024eaac55e5a89e299253b929f1e7e08e68dc69fadf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
