# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16b62ab3b698157880eeb15708e500cc6e8ae0fba56de407dd57902240a6c18d9e815d8e16dbd4a6a0f6478b164ba94ba7eb5aef499144341945d0c0cd1d708d

test:
  secret_key_base: 8e4ddde619dafa3b034dd20f52cde16d953bec03b055564e3b661258ad3c15417cf416ae22af68079240b99c6cbe24c2730814ce28aa8d64e79fd6a5a96601b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
