# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6783701b5b6443bf68a47ef6f131111c31787b353e5d3e83050c533d16a8c230895118963a4f676f336df74378ccba90f7766b2ccd1165787d6e15b6b94bab62

test:
  secret_key_base: fdcb9f609fc08886cd45aa61292f5f2fe7714440194b0adb92c34a653303520ef774a977442773555ca64fe749eb4adb82c50ba3124a2af31bb0b3cf1bd1132d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
